version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: meuSQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: caio1234
      MYSQL_DATABASE: elvenworks
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    environment:
      DATABASE_URL: "mysql://root:caio1234@mysql:3306/elvenworks"
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    command: ["npm", "start"]  
volumes:
  mysql_data: